INSERT INTO EVENTOS (COD_EVENTO, FECHA, LUGAR, NUM_ENTRADAS_DISPONIBLES) VALUES ('E001', TO_DATE('2026-02-01','YYYY-MM-DD'), 'Madrid', 500);
INSERT INTO EVENTOS (COD_EVENTO, FECHA, LUGAR, NUM_ENTRADAS_DISPONIBLES) VALUES ('E002', TO_DATE('2026-03-10','YYYY-MM-DD'), 'Barcelona', 300);

INSERT INTO COMBATES (COD_COMBATE, FECHA, TIEMPO_DURACION, NUM_KOS, COD_EVENTO) VALUES ('C001', TO_DATE('2026-02-01','YYYY-MM-DD'), '00:30', 2, 'E001');
INSERT INTO COMBATES (COD_COMBATE, FECHA, TIEMPO_DURACION, NUM_KOS, COD_EVENTO) VALUES ('C002', TO_DATE('2026-03-10','YYYY-MM-DD'), '00:45', 3, 'E002');

INSERT INTO BARES (COD_BAR, NOMBRE, COMIDA, BEBIDAS, COD_EVENTO) VALUES ('B001', 'Bar Central', 'Tapas', 'Cerveza', 'E001');
INSERT INTO BARES (COD_BAR, NOMBRE, COMIDA, BEBIDAS, COD_EVENTO) VALUES ('B002', 'Bar Mar', 'Bocadillos', 'Refrescos', 'E002');

INSERT INTO ANIMADORAS (NIF, GRUPO, NOMBRE) VALUES ('12345678', 'G1', 'Lucia');
INSERT INTO ANIMADORAS (NIF, GRUPO, NOMBRE) VALUES ('87654321', 'G2', 'Maria');

INSERT INTO ASISTEN (COD_EVENTO, NIF) VALUES ('E001', '12345678');
INSERT INTO ASISTEN (COD_EVENTO, NIF) VALUES ('E002', '87654321');

INSERT INTO ARBITROS (ID_ARBITRO, NUM_PARTIDOS_ARBITRADOS, NUM_DETENCIONES) VALUES (1, 10, 2);
INSERT INTO ARBITROS (ID_ARBITRO, NUM_PARTIDOS_ARBITRADOS, NUM_DETENCIONES) VALUES (2, 5, 1);

INSERT INTO ARBITRAN (COD_COMBATE, ID_ARBITRO) VALUES ('C001', 1);
INSERT INTO ARBITRAN (COD_COMBATE, ID_ARBITRO) VALUES ('C002', 2);

INSERT INTO ENTRENADORES (DNI, NUM_ENTRENAMIENTOS) VALUES ('11112222', 15);
INSERT INTO ENTRENADORES (DNI, NUM_ENTRENAMIENTOS) VALUES ('33334444', 20);

INSERT INTO LUCHADORES (COD_LUCHADOR, ANOS_ENTRENANDO, DNI_ENTRENADOR) VALUES ('L001', 5, '11112222');
INSERT INTO LUCHADORES (COD_LUCHADOR, ANOS_ENTRENANDO, DNI_ENTRENADOR) VALUES ('L002', 3, '33334444');

INSERT INTO PARTICIPAN (COD_COMBATE, COD_LUCHADOR, GOLPES_DADOS, GOLPES_RECIBIDOS) VALUES ('C001', 'L001', 12, 8);
INSERT INTO PARTICIPAN (COD_COMBATE, COD_LUCHADOR, GOLPES_DADOS, GOLPES_RECIBIDOS) VALUES ('C002', 'L002', 10, 15);

INSERT INTO BOXEO (COD_LUCHADOR, ONZAS) VALUES ('L001', 12);
INSERT INTO BOXEO (COD_LUCHADOR, ONZAS) VALUES ('L002', 10);

INSERT INTO JIUJITSU (COD_LUCHADOR, CINTURON) VALUES ('L001', 'AZUL');
INSERT INTO JIUJITSU (COD_LUCHADOR, CINTURON) VALUES ('L002', 'MORADO');

INSERT INTO JUDO (COD_LUCHADOR, CINTURON) VALUES ('L001', 'MARRON');
INSERT INTO JUDO (COD_LUCHADOR, CINTURON) VALUES ('L002', 'NEGRO');

INSERT INTO MUAYTHAI (COD_LUCHADOR) VALUES ('L001');
INSERT INTO MUAYTHAI (COD_LUCHADOR) VALUES ('L002');


/* 

Los DNI y los NIF ha futuro deberian tener regulacion para que solo se escriban siguiuendo su orden.

CONSTRAINT CHK1_ANIMADORAS CHECK (REGEXP_LIKE(NIF, '^[0-9]{8}$'))
CONSTRAINT CHK1_ASISTEN CHECK (REGEXP_LIKE(NIF, '^[0-9]{8}$'))
CONSTRAINT CHK1_ENTRENADORES CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}$'))

Las onzas tienen unas medidas que seran comprobadas para que no se salga de linea

CONSTRAINT CHK1_BOXEO CHECK ((ONZAS BETWEEN 8 AND 10) OR ONZAS = 12 OR (ONZAS BETWEEN 14 AND 16))

Se comprobara que los cinturones sean de los colores adecuados

CONSTRAINT CHK1_JIUJITSU CHECK (CINTURON IN ('BLANCO', 'AZUL', 'MORADO', 'MARRON', 'NEGRO'))
);
CONSTRAINT CHK1_JUDO CHECK (CINTURON IN ('BLANCO', 'AZUL', 'MORADO', 'MARRON', 'NEGRO'))

*/
/*
 Insert para las tablas de mysql
 
 INSERT INTO EVENTOS VALUES ('E001', '2026-02-01', 'Madrid', 500);
INSERT INTO EVENTOS VALUES ('E002', '2026-03-10', 'Barcelona', 300);

INSERT INTO COMBATES VALUES ('C001', '2026-02-01', '00:30', 2, 'E001');
INSERT INTO COMBATES VALUES ('C002', '2026-03-10', '00:45', 3, 'E002');

INSERT INTO BARES VALUES ('B001', 'Bar Central', 'Tapas', 'Cerveza', 'E001');
INSERT INTO BARES VALUES ('B002', 'Bar Mar', 'Bocadillos', 'Refrescos', 'E002');

INSERT INTO ANIMADORAS VALUES ('12345678', 'G1', 'Lucia');
INSERT INTO ANIMADORAS VALUES ('87654321', 'G2', 'Maria');

INSERT INTO ASISTEN VALUES ('E001', '12345678');
INSERT INTO ASISTEN VALUES ('E002', '87654321');

INSERT INTO ARBITROS VALUES (1, 10, 2);
INSERT INTO ARBITROS VALUES (2, 5, 1);

INSERT INTO ARBITRAN VALUES ('C001', 1);
INSERT INTO ARBITRAN VALUES ('C002', 2);

INSERT INTO ENTRENADORES VALUES ('11112222', 15);
INSERT INTO ENTRENADORES VALUES ('33334444', 20);

INSERT INTO LUCHADORES VALUES ('L001', 5, '11112222');
INSERT INTO LUCHADORES VALUES ('L002', 3, '33334444');

INSERT INTO PARTICIPAN VALUES ('C001', 'L001', 12, 8);
INSERT INTO PARTICIPAN VALUES ('C002', 'L002', 10, 15);

INSERT INTO BOXEO VALUES ('L001', 12);
INSERT INTO BOXEO VALUES ('L002', 10);

INSERT INTO JIUJITSU VALUES ('L001', 'AZUL');
INSERT INTO JIUJITSU VALUES ('L002', 'MORADO');

INSERT INTO JUDO VALUES ('L001', 'MARRON');
INSERT INTO JUDO VALUES ('L002', 'NEGRO');

INSERT INTO MUAYTHAI VALUES ('L001');
INSERT INTO MUAYTHAI VALUES ('L002');

Futuros restricciones para las tablas de mysql

ALTER TABLE EVENTOS
ADD CONSTRAINT CHK_EVENTOS_ENTRADAS
CHECK (NUM_ENTRADAS_DISPONIBLES >= 0);

ALTER TABLE COMBATES
ADD CONSTRAINT CHK_COMBATES_KOS
CHECK (NUM_KOS >= 0);

ALTER TABLE PARTICIPAN
ADD CONSTRAINT CHK_PARTICIPAN_GOLPES
CHECK (GOLPES_DADOS >= 0 AND GOLPES_RECIBIDOS >= 0);

ALTER TABLE ARBITROS
ADD CONSTRAINT CHK_ARBITROS_VALORES
CHECK (NUM_PARTIDOS_ARBITRADOS >= 0 AND NUM_DETENCIONES >= 0);

UPDATE EVENTOS
SET NUM_ENTRADAS_DISPONIBLES = 0
WHERE NUM_ENTRADAS_DISPONIBLES < 0;

UPDATE COMBATES
SET NUM_KOS = 0
WHERE NUM_KOS < 0;

UPDATE PARTICIPAN
SET GOLPES_DADOS = 0
WHERE GOLPES_DADOS < 0;

UPDATE PARTICIPAN
SET GOLPES_RECIBIDOS = 0
WHERE GOLPES_RECIBIDOS < 0;

UPDATE ARBITROS
SET NUM_PARTIDOS_ARBITRADOS = 0
WHERE NUM_PARTIDOS_ARBITRADOS < 0;

UPDATE ARBITROS
SET NUM_DETENCIONES = 0
WHERE NUM_DETENCIONES < 0;


*/
