

CREATE TABLE EVENTOS (
    COD_EVENTO VARCHAR2(20),
    FECHA DATE,
    LUGAR VARCHAR2(20),
    NUM_ENTRADAS_DISPONIBLES NUMBER(6),
    CONSTRAINT PK_EVENTOS PRIMARY KEY (COD_EVENTO)
);

CREATE TABLE COMBATES (
    COD_COMBATE VARCHAR2(20),
    FECHA DATE,
    TIEMPO_DURACION VARCHAR2(10),
    NUM_KOS NUMBER(3),
    COD_EVENTO VARCHAR2(20),
    CONSTRAINT PK_COMBATES PRIMARY KEY (COD_COMBATE),
    CONSTRAINT FK1_COMBATES FOREIGN KEY (COD_EVENTO)
        REFERENCES EVENTOS (COD_EVENTO)
);

CREATE TABLE BARES (
    COD_BAR VARCHAR2(20),
    NOMBRE VARCHAR2(20),
    COMIDA VARCHAR2(20),
    BEBIDAS VARCHAR2(20),
    COD_EVENTO VARCHAR2(20),
    CONSTRAINT PK_BARES PRIMARY KEY (COD_BAR),
    CONSTRAINT FK1_BARES FOREIGN KEY (COD_EVENTO)
        REFERENCES EVENTOS (COD_EVENTO)
);

CREATE TABLE ANIMADORAS (
    NIF VARCHAR2(9),
    GRUPO VARCHAR2(4),
    NOMBRE VARCHAR2(20),
    CONSTRAINT PK_ANIMADORAS PRIMARY KEY (NIF)
);

CREATE TABLE ASISTEN (
    COD_EVENTO VARCHAR2(20),
    NIF VARCHAR2(9),
    CONSTRAINT PK_ASISTEN PRIMARY KEY (COD_EVENTO, NIF),
    CONSTRAINT FK1_ASISTEN FOREIGN KEY (COD_EVENTO)
        REFERENCES EVENTOS (COD_EVENTO),
    CONSTRAINT FK2_ASISTEN FOREIGN KEY (NIF)
        REFERENCES ANIMADORAS (NIF)
);

CREATE TABLE ARBITROS (
    ID_ARBITRO NUMBER(5),
    NUM_PARTIDOS_ARBITRADOS NUMBER(4),
    NUM_DETENCIONES NUMBER(4),
    CONSTRAINT PK_ARBITROS PRIMARY KEY (ID_ARBITRO)
);

CREATE TABLE ARBITRAN (
    COD_COMBATE VARCHAR2(20),
    ID_ARBITRO NUMBER(5),
    CONSTRAINT PK_ARBITRAN PRIMARY KEY (COD_COMBATE, ID_ARBITRO),
    CONSTRAINT FK1_ARBITRAN FOREIGN KEY (COD_COMBATE)
        REFERENCES COMBATES (COD_COMBATE),
    CONSTRAINT FK2_ARBITRAN FOREIGN KEY (ID_ARBITRO)
        REFERENCES ARBITROS (ID_ARBITRO)
);

CREATE TABLE ENTRENADORES (
    DNI VARCHAR2(9),
    NUM_ENTRENAMIENTOS NUMBER(4),
    CONSTRAINT PK_ENTRENADORES PRIMARY KEY (DNI)

);

CREATE TABLE LUCHADORES (
    COD_LUCHADOR VARCHAR2(5),
    ANOS_ENTRENANDO NUMBER(2),
    DNI_ENTRENADOR VARCHAR2(9),
    CONSTRAINT PK_LUCHADORES PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_LUCHADORES FOREIGN KEY (DNI_ENTRENADOR)
        REFERENCES ENTRENADORES (DNI)

);

CREATE TABLE PARTICIPAN (
    COD_COMBATE VARCHAR2(20),
    COD_LUCHADOR VARCHAR2(5),
    GOLPES_DADOS NUMBER(3),
    GOLPES_RECIBIDOS NUMBER(3),
    CONSTRAINT PK_PARTICIPAN PRIMARY KEY (COD_COMBATE, COD_LUCHADOR),
    CONSTRAINT FK1_PARTICIPAN FOREIGN KEY (COD_COMBATE)
        REFERENCES COMBATES (COD_COMBATE),
    CONSTRAINT FK2_PARTICIPAN FOREIGN KEY (COD_LUCHADOR)
        REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE BOXEO (
    COD_LUCHADOR VARCHAR2(5),
    ONZAS NUMBER(2),
    CONSTRAINT PK_BOXEO PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_BOXEO FOREIGN KEY (COD_LUCHADOR)
        REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE JIUJITSU (
    COD_LUCHADOR VARCHAR2(5),
    CINTURON VARCHAR2(6),
    CONSTRAINT PK_JIUJITSU PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_JIUJITSU FOREIGN KEY (COD_LUCHADOR)
        REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE JUDO (
    COD_LUCHADOR VARCHAR2(5),
    CINTURON VARCHAR2(6),
    CONSTRAINT PK_JUDO PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_JUDO FOREIGN KEY (COD_LUCHADOR)
        REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE MUAYTHAI (
    COD_LUCHADOR VARCHAR2(5),
    CONSTRAINT PK_MUAYTHAI PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_MUAYTHAI FOREIGN KEY (COD_LUCHADOR)
        REFERENCES LUCHADORES (COD_LUCHADOR)
)