-- create database ejcombate;
-- create user 'dummy'@'%' identified by 'dummy';
-- grant all on db_exampleName.* to 'dummy'@'%';

CREATE TABLE EVENTOS (
    COD_EVENTO VARCHAR(20),
    FECHA DATE,
    LUGAR VARCHAR(20),
    NUM_ENTRADAS_DISPONIBLES NUMERIC(6),
    CONSTRAINT PK_EVENTOS PRIMARY KEY (COD_EVENTO)
);

CREATE TABLE ARBITROS (
    ID_ARBITRO NUMERIC(5),
    NUM_PARTIDOS_ARBITRADOS NUMERIC(4),
    NUM_DETENCIONES NUMERIC(4),
    CONSTRAINT PK_ARBITROS PRIMARY KEY (ID_ARBITRO)
);

CREATE TABLE COMBATES (
    COD_COMBATE VARCHAR(20),
    FECHA DATE,
    TIEMPO_DURACION VARCHAR(10),
    NUM_KOS NUMERIC(3),
    ID_ARBITRO NUMERIC(5),
    CONSTRAINT PK_COMBATES PRIMARY KEY (COD_COMBATE),
    CONSTRAINT FK1_COMBATES FOREIGN KEY (ID_ARBITRO) REFERENCES ARBITROS (ID_ARBITRO)
);

CREATE TABLE REALIZA (
	COD_EVENTO VARCHAR(20),
	COD_COMBATE VARCHAR(20),
	CONSTRAINT PK_REALIZA PRIMARY KEY(COD_EVENTO, COD_COMBATE),
	CONSTRAINT FK1_REALIZA FOREIGN KEY (COD_EVENTO) REFERENCES EVENTOS (COD_EVENTO),
	CONSTRAINT FK2_REALIZA FOREIGN KEY (COD_COMBATE) REFERENCES COMBATES (COD_COMBATE)
);

CREATE TABLE BARES (
    COD_BAR VARCHAR(20),
    NOMBRE VARCHAR(20),
    COMIDA VARCHAR(20),
    BEBIDAS VARCHAR(20),
    COD_EVENTO VARCHAR(20),
    CONSTRAINT PK_BARES PRIMARY KEY (COD_BAR),
    CONSTRAINT FK1_BARES FOREIGN KEY (COD_EVENTO) REFERENCES EVENTOS (COD_EVENTO)
);

CREATE TABLE ANIMADORAS (
    NIF VARCHAR(9),
    GRUPO VARCHAR(4),
    NOMBRE VARCHAR(20),
    CONSTRAINT PK_ANIMADORAS PRIMARY KEY (NIF)
);

CREATE TABLE ASISTEN (
    COD_EVENTO VARCHAR(20),
    NIF VARCHAR(9),
    CONSTRAINT PK_ASISTEN PRIMARY KEY (COD_EVENTO, NIF),
    CONSTRAINT FK1_ASISTEN FOREIGN KEY (COD_EVENTO) REFERENCES EVENTOS (COD_EVENTO),
    CONSTRAINT FK2_ASISTEN FOREIGN KEY (NIF) REFERENCES ANIMADORAS (NIF)
);

CREATE TABLE ENTRENADORES (
    DNI VARCHAR(9),
    NUM_ENTRENAMIENTOS NUMERIC(4),
    CONSTRAINT PK_ENTRENADORES PRIMARY KEY (DNI)
);

CREATE TABLE LUCHADORES (
    COD_LUCHADOR VARCHAR(5),
    ANOS_ENTRENANDO NUMERIC(2),
    DNI_ENTRENADOR VARCHAR(9),
    CONSTRAINT PK_LUCHADORES PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_LUCHADORES FOREIGN KEY (DNI_ENTRENADOR) REFERENCES ENTRENADORES (DNI)
);

CREATE TABLE ENFRENTA (
	COD_LUCHADOR1 VARCHAR(5),
	COD_LUCHADOR2 VARCHAR(5),
	CONSTRAINT PK_ENFRENTA PRIMARY KEY (COD_LUCHADOR1, COD_LUCHADOR2),
	CONSTRAINT FK1_ENFRENTA FOREIGN KEY (COD_LUCHADOR1) REFERENCES LUCHADORES (COD_LUCHADOR),
    CONSTRAINT FK2_ENFRENTA FOREIGN KEY (COD_LUCHADOR2) REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE PARTICIPAN (
    COD_COMBATE VARCHAR(20),
    COD_LUCHADOR VARCHAR(5),
    GOLPES_DADOS NUMERIC(3),
    GOLPES_RECIBIDOS NUMERIC(3),
    CONSTRAINT PK_PARTICIPAN PRIMARY KEY (COD_COMBATE, COD_LUCHADOR),
    CONSTRAINT FK1_PARTICIPAN FOREIGN KEY (COD_COMBATE) REFERENCES COMBATES (COD_COMBATE),
    CONSTRAINT FK2_PARTICIPAN FOREIGN KEY (COD_LUCHADOR) REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE BOXEO (
    COD_LUCHADOR VARCHAR(5),
    ONZAS NUMERIC(2),
    CONSTRAINT PK_BOXEO PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_BOXEO FOREIGN KEY (COD_LUCHADOR) REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE JIUJITSU (
    COD_LUCHADOR VARCHAR(5),
    CINTURON VARCHAR(6),
    CONSTRAINT PK_JIUJITSU PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_JIUJITSU FOREIGN KEY (COD_LUCHADOR) REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE JUDO (
    COD_LUCHADOR VARCHAR(5),
    CINTURON VARCHAR(6),
    CONSTRAINT PK_JUDO PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_JUDO FOREIGN KEY (COD_LUCHADOR) REFERENCES LUCHADORES (COD_LUCHADOR)
);

CREATE TABLE MUAYTHAI (
    COD_LUCHADOR VARCHAR(5),
    CONSTRAINT PK_MUAYTHAI PRIMARY KEY (COD_LUCHADOR),
    CONSTRAINT FK1_MUAYTHAI FOREIGN KEY (COD_LUCHADOR) REFERENCES LUCHADORES (COD_LUCHADOR)
);
